/** Audited upstream source evidence and the native help commands sampled for drift. */
export const sourceEvidence = Object.freeze({
	repository: "vercel-labs/agent-browser",
	upstreamHead: "aff6125c023b810ea3f2e5deec5379e9a4270bdc",
	upstreamPackageVersion: "0.38.1",
	inspectedSources: Object.freeze([
		"agent-browser --version",
		"agent-browser --help",
		"selected agent-browser <command> --help output",
		"agent-browser a11y --help",
		"agent-browser mcp --help",
		"agent-browser plugin --help",
		"agent-browser skills list",
		"agent-browser skills get core --full",
		"agent-browser skills get derive-client --full",
		"agent-browser skills get webmcp-gen --full",
		"README.md",
		"CHANGELOG.md",
		"agent-browser.schema.json",
		"bin/agent-browser.js",
		"cli/src/ca_bundle.rs",
		"cli/src/commands.rs",
		"cli/src/mcp.rs",
		"cli/src/flags.rs",
		"cli/src/read.rs",
		"cli/src/doctor/ffmpeg.rs",
		"cli/src/doctor/webgpu.rs",
		"cli/src/native/actions.rs",
		"cli/src/native/a11y/mod.rs",
		"cli/src/native/browser.rs",
		"cli/src/native/tab_binding.rs",
		"cli/src/native/daemon.rs",
		"cli/src/native/element.rs",
		"cli/src/native/recording.rs",
		"cli/src/native/snapshot.rs",
		"cli/src/native/interaction.rs",
		"cli/src/native/screenshot.rs",
		"cli/src/native/stream/cdp_loop.rs",
		"cli/src/native/stream/dashboard.rs",
		"cli/src/native/test_fixtures/webmcp_frame_probe.html",
		"cli/src/native/test_fixtures/webmcp_probe.html",
		"cli/src/native/webmcp.rs",
		"cli/src/output.rs",
		"docs/src/app/webgpu/page.mdx",
		"docs/src/app/webmcp/page.mdx",
		"docs/src/app/network/page.mdx",
		"docs/src/app/proxy/page.mdx",
		"docs/src/app/selectors/page.mdx",
		"docs/src/app/skills/page.mdx",
		"docs/src/app/commands/page.mdx",
		"skill-data/derive-client/SKILL.md",
		"skill-data/core/SKILL.md",
		"skill-data/core/references/video-recording.md",
		"skill-data/protected-vercel-deployments/SKILL.md",
		"skill-data/webmcp-gen/SKILL.md",
		"test/launcher.test.mjs",
		"packages/@agent-browser/eve/README.md",
		"packages/@agent-browser/eve/package.json",
		"packages/@agent-browser/eve/test/extension.test.mjs",
		"packages/@agent-browser/sandbox/README.md",
		"packages/@agent-browser/sandbox/src/shared.ts",
		"packages/@agent-browser/sandbox/src/vercel.ts",
		"packages/@agent-browser/sandbox/src/eve.ts",
	]),
});

const helpCommand = (label, args) => Object.freeze({ label, args: Object.freeze(args) });
export const helpCommands = Object.freeze([
	helpCommand("root help", ["--help"]),
	helpCommand("skills help", ["skills", "--help"]),
	helpCommand("skills list", ["skills", "list"]),
	helpCommand("core skill full", ["skills", "get", "core", "--full"]),
	helpCommand("vercel sandbox skill full", ["skills", "get", "vercel-sandbox", "--full"]),
	helpCommand("protected Vercel deployments skill full", [
		"skills",
		"get",
		"protected-vercel-deployments",
		"--full",
	]),
	helpCommand("WebMCP generation skill full", ["skills", "get", "webmcp-gen", "--full"]),
	helpCommand("open help", ["open", "--help"]),
	helpCommand("read help", ["read", "--help"]),
	helpCommand("click help", ["click", "--help"]),
	helpCommand("key help", ["key", "--help"]),
	helpCommand("scroll help", ["scroll", "--help"]),
	helpCommand("scrollinto help", ["scrollinto", "--help"]),
	helpCommand("keydown help", ["keydown", "--help"]),
	helpCommand("keyup help", ["keyup", "--help"]),
	helpCommand("get help", ["get", "--help"]),
	helpCommand("is help", ["is", "--help"]),
	helpCommand("mouse help", ["mouse", "--help"]),
	helpCommand("drag help", ["drag", "--help"]),
	helpCommand("set help", ["set", "--help"]),
	helpCommand("tab help", ["tab", "--help"]),
	helpCommand("snapshot help", ["snapshot", "--help"]),
	helpCommand("eval help", ["eval", "--help"]),
	helpCommand("wait help", ["wait", "--help"]),
	helpCommand("screenshot help", ["screenshot", "--help"]),
	helpCommand("pdf help", ["pdf", "--help"]),
	helpCommand("close help", ["close", "--help"]),
	helpCommand("find help", ["find", "--help"]),
	helpCommand("network help", ["network", "--help"]),
	helpCommand("cookies help", ["cookies", "--help"]),
	helpCommand("storage help", ["storage", "--help"]),
	helpCommand("state help", ["state", "--help"]),
	helpCommand("session help", ["session", "--help"]),
	helpCommand("frame help", ["frame", "--help"]),
	helpCommand("dialog help", ["dialog", "--help"]),
	helpCommand("window help", ["window", "--help"]),
	helpCommand("keyboard help", ["keyboard", "--help"]),
	helpCommand("batch help", ["batch", "--help"]),
	helpCommand("auth help", ["auth", "--help"]),
	helpCommand("stream help", ["stream", "--help"]),
	helpCommand("dashboard help", ["dashboard", "--help"]),
	helpCommand("chat help", ["chat", "--help"]),
	helpCommand("doctor help", ["doctor", "--help"]),
	helpCommand("diff help", ["diff", "--help"]),
	helpCommand("trace help", ["trace", "--help"]),
	helpCommand("profiler help", ["profiler", "--help"]),
	helpCommand("record help", ["record", "--help"]),
	helpCommand("console help", ["console", "--help"]),
	helpCommand("errors help", ["errors", "--help"]),
	helpCommand("a11y help", ["a11y", "--help"]),
	helpCommand("clipboard help", ["clipboard", "--help"]),
	helpCommand("tap help", ["tap", "--help"]),
	helpCommand("swipe help", ["swipe", "--help"]),
	helpCommand("device help", ["device", "--help"]),
	helpCommand("install help", ["install", "--help"]),
	helpCommand("upgrade help", ["upgrade", "--help"]),
	helpCommand("profiles help", ["profiles", "--help"]),
	helpCommand("mcp help", ["mcp", "--help"]),
	helpCommand("plugin help", ["plugin", "--help"]),
]);
