/** Global native flags, launch configuration, provider, policy, and environment inventory. */
import { root, section } from "./capability-section.mjs";
export const optionsAndEnv = section(
	"options-and-env",
	"Global flags, config, providers, policy, and environment",
	[
		"--profile <name|path>",
		"AGENT_BROWSER_PROFILE",
		"--session <name>",
		"AGENT_BROWSER_SESSION",
		"--namespace <name>",
		"AGENT_BROWSER_NAMESPACE",
		"--restore [name]",
		"AGENT_BROWSER_RESTORE",
		"--restore-save <policy>",
		"AGENT_BROWSER_RESTORE_SAVE",
		"--restore-check-url <glob>",
		"AGENT_BROWSER_RESTORE_CHECK_URL",
		"--restore-check-text <txt>",
		"AGENT_BROWSER_RESTORE_CHECK_TEXT",
		"--restore-check-fn <js>",
		"AGENT_BROWSER_RESTORE_CHECK_FN",
		"--session-name <name>",
		"AGENT_BROWSER_SESSION_NAME",
		"--state <path>",
		"AGENT_BROWSER_STATE",
		"--auto-connect",
		"AGENT_BROWSER_AUTO_CONNECT",
		"--pin-tab",
		"--no-pin-tab",
		"AGENT_BROWSER_PIN_TAB",
		"--headers <json>",
		"--init-script <path>",
		"AGENT_BROWSER_INIT_SCRIPTS",
		"--enable <feature>",
		"AGENT_BROWSER_ENABLE",
		"--executable-path <path>",
		"AGENT_BROWSER_EXECUTABLE_PATH",
		"--extension <path>",
		"AGENT_BROWSER_EXTENSIONS",
		"--args <args>",
		"AGENT_BROWSER_ARGS",
		"--user-agent <ua>",
		"AGENT_BROWSER_USER_AGENT",
		"--proxy <server>",
		"AGENT_BROWSER_PROXY",
		"HTTP_PROXY",
		"HTTPS_PROXY",
		"ALL_PROXY",
		"--proxy-bypass <hosts>",
		"AGENT_BROWSER_PROXY_BYPASS",
		"NO_PROXY",
		"--ignore-https-errors",
		"AGENT_BROWSER_IGNORE_HTTPS_ERRORS",
		"--ca-cert <path>",
		"--no-ca-cert",
		"AGENT_BROWSER_CA_CERT",
		"AGENT_BROWSER_CLEAR_CA_CERT",
		"--allow-file-access",
		"AGENT_BROWSER_ALLOW_FILE_ACCESS",
		"--hide-scrollbars <bool>",
		"--headed",
		"AGENT_BROWSER_HEADED",
		"--webgpu",
		"AGENT_BROWSER_WEBGPU",
		"--no-webmcp",
		"AGENT_BROWSER_NO_WEBMCP",
		"noWebmcp",
		"AGENT_BROWSER_NO_XVFB",
		'"webgpu": true',
		"--cdp <port|url>",
		"--color-scheme <scheme>",
		"AGENT_BROWSER_COLOR_SCHEME",
		"--download-path <path>",
		"AGENT_BROWSER_DOWNLOAD_PATH",
		"--engine <name>",
		"AGENT_BROWSER_ENGINE",
		"--input-mode <mode>",
		"--no-auto-dialog",
		"AGENT_BROWSER_NO_AUTO_DIALOG",
		"--json",
		"AGENT_BROWSER_JSON",
		"--annotate",
		"AGENT_BROWSER_ANNOTATE",
		"--screenshot-dir <path>",
		"AGENT_BROWSER_SCREENSHOT_DIR",
		"--screenshot-quality <n>",
		"AGENT_BROWSER_SCREENSHOT_QUALITY",
		"--screenshot-format <fmt>",
		"AGENT_BROWSER_SCREENSHOT_FORMAT",
		"--content-boundaries",
		"AGENT_BROWSER_CONTENT_BOUNDARIES",
		"--max-output <chars>",
		"AGENT_BROWSER_MAX_OUTPUT",
		"--allowed-domains <list>",
		"AGENT_BROWSER_ALLOWED_DOMAINS",
		"--action-policy <path>",
		"AGENT_BROWSER_ACTION_POLICY",
		"--confirm-actions <list>",
		"AGENT_BROWSER_CONFIRM_ACTIONS",
		"--confirm-interactive",
		"AGENT_BROWSER_CONFIRM_INTERACTIVE",
		"-p, --provider <name>",
		"AGENT_BROWSER_PROVIDER",
		"AGENT_BROWSER_PLUGINS",
		"browserbase",
		"kernel",
		"browseruse",
		"browserless",
		"agentcore",
		"--device <name>",
		"AGENT_BROWSER_IOS_DEVICE",
		"agent-browser -p ios device list",
		"agent-browser -p ios swipe up",
		"agent-browser -p ios tap @e1",
		"--model <name>",
		"AI_GATEWAY_MODEL",
		"-v, --verbose",
		"-q, --quiet",
		"--debug",
		"AGENT_BROWSER_DEBUG",
		"AGENT_BROWSER_CONFIG",
		"AGENT_BROWSER_DEFAULT_TIMEOUT",
		"--idle-timeout <ms>",
		"AGENT_BROWSER_AUTOSAVE_INTERVAL_MS",
		"AGENT_BROWSER_STREAM_PORT",
		"AGENT_BROWSER_STREAM_QUALITY",
		"AGENT_BROWSER_STREAM_MAX_WIDTH",
		"AGENT_BROWSER_STREAM_MAX_HEIGHT",
		"AGENT_BROWSER_IDLE_TIMEOUT_MS",
		"AGENT_BROWSER_ENCRYPTION_KEY",
		"AGENT_BROWSER_STATE_EXPIRE_DAYS",
		"AGENT_BROWSER_IOS_UDID",
		"AI_GATEWAY_URL",
		"AI_GATEWAY_API_KEY",
		"BROWSERBASE_API_KEY",
		"BROWSERBASE_PROJECT_ID",
		"BROWSERLESS_API_KEY",
		"BROWSERLESS_API_URL",
		"BROWSERLESS_BROWSER_TYPE",
		"BROWSERLESS_STEALTH",
		"BROWSERLESS_TTL",
		"BROWSER_USE_API_KEY",
		"KERNEL_API_KEY",
		"KERNEL_HEADLESS",
		"KERNEL_STEALTH",
		"KERNEL_TIMEOUT_SECONDS",
		"KERNEL_PROFILE_NAME",
		"AGENTCORE_API_KEY",
		"AGENTCORE_REGION",
		"AGENTCORE_BROWSER_ID",
		"AGENTCORE_PROFILE_ID",
		"AGENTCORE_SESSION_TIMEOUT",
		"AWS_PROFILE",
		"AWS_ACCESS_KEY_ID",
		"AWS_SECRET_ACCESS_KEY",
		"AWS_SESSION_TOKEN",
		"AWS_REGION",
		"AWS_DEFAULT_REGION",
	],
	[
		root("--profile <name|path>"),
		root("AGENT_BROWSER_PROFILE"),
		root("--session <name>"),
		root("AGENT_BROWSER_SESSION"),
		root("--namespace <name>"),
		root("AGENT_BROWSER_NAMESPACE"),
		root("--restore [name]"),
		root("AGENT_BROWSER_RESTORE"),
		root("--restore-save <policy>"),
		root("AGENT_BROWSER_RESTORE_SAVE"),
		root("--restore-check-url <glob>"),
		root("AGENT_BROWSER_RESTORE_CHECK_URL"),
		root("--restore-check-text <txt>"),
		root("AGENT_BROWSER_RESTORE_CHECK_TEXT"),
		root("--restore-check-fn <js>"),
		root("AGENT_BROWSER_RESTORE_CHECK_FN"),
		root("--session-name <name>"),
		root("AGENT_BROWSER_SESSION_NAME"),
		root("--state <path>"),
		root("AGENT_BROWSER_STATE"),
		root("--auto-connect"),
		root("AGENT_BROWSER_AUTO_CONNECT"),
		root("--pin-tab"),
		root("--no-pin-tab"),
		root("AGENT_BROWSER_PIN_TAB"),
		root("--headers <json>"),
		root("--init-script <path>"),
		root("AGENT_BROWSER_INIT_SCRIPTS"),
		root("--enable <feature>"),
		root("AGENT_BROWSER_ENABLE"),
		root("--executable-path <path>"),
		root("AGENT_BROWSER_EXECUTABLE_PATH"),
		root("--extension <path>"),
		root("AGENT_BROWSER_EXTENSIONS"),
		root("--args <args>"),
		root("AGENT_BROWSER_ARGS"),
		root("--user-agent <ua>"),
		root("AGENT_BROWSER_USER_AGENT"),
		root("--proxy <server>"),
		root("AGENT_BROWSER_PROXY"),
		root("HTTP_PROXY / HTTPS_PROXY"),
		root("ALL_PROXY"),
		root("--proxy-bypass <hosts>"),
		root("AGENT_BROWSER_PROXY_BYPASS"),
		root("NO_PROXY"),
		root("--ignore-https-errors"),
		root("AGENT_BROWSER_IGNORE_HTTPS_ERRORS"),
		root("--ca-cert <path>"),
		root("--no-ca-cert"),
		root("AGENT_BROWSER_CA_CERT"),
		root("AGENT_BROWSER_CLEAR_CA_CERT"),
		root("--allow-file-access"),
		root("AGENT_BROWSER_ALLOW_FILE_ACCESS"),
		root("--hide-scrollbars <bool>"),
		root("--headed"),
		root("AGENT_BROWSER_HEADED"),
		root("--webgpu"),
		root("AGENT_BROWSER_WEBGPU"),
		root("--no-webmcp"),
		root("AGENT_BROWSER_NO_WEBMCP"),
		root("--cdp <port|url>"),
		root("--color-scheme <scheme>"),
		root("AGENT_BROWSER_COLOR_SCHEME"),
		root("--download-path <path>"),
		root("AGENT_BROWSER_DOWNLOAD_PATH"),
		root("--engine <name>"),
		root("AGENT_BROWSER_ENGINE"),
		root("--input-mode <mode>"),
		root("--no-auto-dialog"),
		root("AGENT_BROWSER_NO_AUTO_DIALOG"),
		root("--json"),
		root("AGENT_BROWSER_JSON"),
		root("--annotate"),
		root("AGENT_BROWSER_ANNOTATE"),
		root("--screenshot-dir <path>"),
		root("AGENT_BROWSER_SCREENSHOT_DIR"),
		root("--screenshot-quality <n>"),
		root("AGENT_BROWSER_SCREENSHOT_QUALITY"),
		root("--screenshot-format <fmt>"),
		root("AGENT_BROWSER_SCREENSHOT_FORMAT"),
		root("--content-boundaries"),
		root("AGENT_BROWSER_CONTENT_BOUNDARIES"),
		root("--max-output <chars>"),
		root("AGENT_BROWSER_MAX_OUTPUT"),
		root("--allowed-domains <list>"),
		root("AGENT_BROWSER_ALLOWED_DOMAINS"),
		root("--action-policy <path>"),
		root("AGENT_BROWSER_ACTION_POLICY"),
		root("--confirm-actions <list>"),
		root("AGENT_BROWSER_CONFIRM_ACTIONS"),
		root("--confirm-interactive"),
		root("AGENT_BROWSER_CONFIRM_INTERACTIVE"),
		root("--provider <name>"),
		root("AGENT_BROWSER_PROVIDER"),
		root("AGENT_BROWSER_PLUGINS"),
		root("agent-browser -p ios device list"),
		root("agent-browser -p ios swipe up"),
		root("agent-browser -p ios tap @e1"),
		root("--device <name>"),
		root("AGENT_BROWSER_IOS_DEVICE"),
		root("--model <name>"),
		root("AI_GATEWAY_MODEL"),
		root("--verbose"),
		root("--quiet"),
		root("--debug"),
		root("AGENT_BROWSER_DEBUG"),
		root("--config <path>"),
		root("AGENT_BROWSER_CONFIG"),
		root("AGENT_BROWSER_DEFAULT_TIMEOUT"),
		root("AGENT_BROWSER_AUTOSAVE_INTERVAL_MS"),
		root("AGENT_BROWSER_STREAM_PORT"),
		root("AGENT_BROWSER_STREAM_QUALITY"),
		root("AGENT_BROWSER_STREAM_MAX_WIDTH"),
		root("AGENT_BROWSER_STREAM_MAX_HEIGHT"),
		root("AGENT_BROWSER_IDLE_TIMEOUT_MS"),
		root("AGENT_BROWSER_ENCRYPTION_KEY"),
		root("AGENT_BROWSER_STATE_EXPIRE_DAYS"),
		root("AGENT_BROWSER_IOS_UDID"),
		root("AI_GATEWAY_URL"),
		root("AI_GATEWAY_API_KEY"),
	],
);
